### ISSUE TITLE
Repository needs a readme

### ISSUE THREAD

**Issue by twillingham** [danjarvis/shazntr#1]
The repository should have a readme with instructions to install locally.

**Comment by danjarvis** [comment]
Thank you for your submission. This will be addressed shortly!

**Comment by twillingham** [comment]
Why thank you, good sir. You truly are a scholar and a gentleman.

On Wed, May 23, 2012 at 2:35 PM, Dan Jarvis <
reply@reply.github.com

**Comment by danjarvis** [comment]
Added README.md
